import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/themes.css";
import PageLayout from "@/layouts/PageLayout";
import StoreProvider from "@/lib/redux/StoreProvider";
import { getAppSettings } from "@/lib/redux/getAppSettings";
// import { ThemeProvider } from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const appSettings = await getAppSettings();
  const preloadedState = { app: appSettings };

  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ThemeProvider> */}
        <StoreProvider preloadedState={preloadedState}>
          <PageLayout>{children}</PageLayout>
        </StoreProvider>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
